name: Run Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up permissions for script.sh
      run: chmod +x ./script.sh
    - name: Execute script.sh
      run: ./script.sh
      
